# Generated by Django 5.0.3 on 2025-09-19 13:42

import django.db.models.deletion
import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=main_app.models.generate_tracking_number, editable=False, max_length=12, unique=True)),
                ('quantity', models.IntegerField()),
                ('weight', models.FloatField(default=0.5)),
                ('service_type', models.CharField(choices=[('sea', 'Sea Delivery'), ('land', 'Land Delivery'), ('Air', 'Land Delivery')], default='land', max_length=200)),
                ('goods_description', models.TextField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_email', models.EmailField(max_length=200)),
                ('receiver_address', models.CharField(max_length=255)),
                ('date_of_delivery', models.CharField(max_length=255)),
                ('sender_name', models.CharField(max_length=100)),
                ('pickup_address', models.CharField(max_length=255)),
                ('sender_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed_attempt', 'Failed Attempt'), ('returned', 'Returned')], default='pending', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main_app.order')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
