# Generated by Django 5.0.3 on 2025-09-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('sea', 'Sea Delivery'), ('land', 'Land Delivery'), ('Air', 'Air Delivery')], default='land', max_length=200),
        ),
    ]
