# Generated by Django 5.0.3 on 2026-02-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_order_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receiver_email',
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_Phone_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
